(* Generated by makepixels.cc. Do not edit! *)

structure PixelData =
struct
  fun count #"a" = SOME 20
    | count #"b" = SOME 22
    | count #"c" = SOME 14
    | count #"d" = SOME 22
    | count #"e" = SOME 20
    | count #"f" = SOME 16
    | count #"g" = SOME 25
    | count #"h" = SOME 21
    | count #"i" = SOME 13
    | count #"j" = SOME 14
    | count #"k" = SOME 20
    | count #"l" = SOME 15
    | count #"m" = SOME 27
    | count #"n" = SOME 21
    | count #"o" = SOME 20
    | count #"p" = SOME 22
    | count #"q" = SOME 22
    | count #"r" = SOME 15
    | count #"s" = SOME 20
    | count #"t" = SOME 17
    | count #"u" = SOME 21
    | count #"v" = SOME 18
    | count #"w" = SOME 25
    | count #"x" = SOME 18
    | count #"y" = SOME 23
    | count #"z" = SOME 18
    | count _ = NONE
end
