
// Note: In guitar.cc, this file is assembled from guitar-head.cc,
// guitar-tail.cc, and some data generated by gencc.cc. Don't edit
// guitar.cc directly.

#include "guitar.h"

#include <string>
#include <vector>
#include <string_view>
#include <array>
#include <optional>
#include <unordered_map>

#include "util.h"
#include "base/logging.h"

using namespace std;
