

#define T_HOLE 13
#define T_FLOOR 0
#define T_RED 1
#define T_WALL 6
#define T_GREY 8
#define T_GREEN 9
#define T_EXIT 11
#define T_YELLOW 36
#define T_LASER 5
#define T_PANEL 4
#define T_ROUGH 3
#define T_ELECTRIC 2
#define T_ON 16
#define T_OFF 17
#define T_TRANSPORTER 15
#define T_BREAKABLE 14
#define T_HORIZ 19
#define T_VERT 18
#define T_ONE 10
#define T_ZERO 7
#define T_UPDOWN 21
#define T_TOPRIGHT 25
#define T_TOPLEFT 26
#define T_BOTRIGHT 22
#define T_BOTLEFT 23
#define T_LEFTRIGHT 20
#define T_PINK 24
#define T_BBUT 27
#define T_GBUT 28
#define T_RBUT 29
#define T_BUP 33
#define T_BDOWN 30
#define T_GUP 34
#define T_GDOWN 31
#define T_RUP 45
#define T_RDOWN 32
#define T_NULL 255
