name: C/C++ CI

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # https://github.com/actions/virtual-environments/issues/675#issuecomment-610483420
      - run: |
          sudo sed -i 's/azure\.//' /etc/apt/sources.list
          sudo apt-get update
          sudo apt install -y libsdl1.2-dev

      - run: gcc --version

      - name: build
        env:
          LINUX: true
        working-directory: escapex
        run: |
          make
          make screenshot.exe
          make packsound.exe

      - uses: actions/upload-artifact@v2
        with:
          name: escapex-${{ runner.os }}
          path: |
            escapex/*.exe
            escapex/*.png

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2

      # https://github.com/actions/runner/issues/497#issuecomment-640856321
      - name: add mingw to path
        shell: powershell
        run: echo "C:\msys64\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - run: gcc --version

      - name: build SDL
        run: |
          curl http://libsdl.org/release/SDL-1.2.15.tar.gz -o SDL-1.2.15.tar.gz
          tar xfz SDL-1.2.15.tar.gz
          cd SDL-1.2.15
          curl https://git.savannah.gnu.org/cgit/config.git/plain/config.guess -o build-scripts/config.guess
          ./configure --prefix `pwd`/build --build i686-pc-mingw32
          make

      - name: build
        env:
          WIN32: true
        working-directory: escapex
        run: |
          make ZOPFLI=cp SDL=../SDL-1.2.15 WINDRES=windres
          make screenshot.exe
          make packsound.exe

      - uses: actions/upload-artifact@v2
        with:
          name: escapex-${{ runner.os }}
          path: |
            escapex/*.exe
            escapex/*.png

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - run: gcc --version

      - name: build some things
        env:
          LINUX: true
        working-directory: escapex
        run: |
          make esclib.a
          make cclib.a
          make sdlnet.a
          make sdlutil.a
          make screenshot.exe
          make packsound.exe

      - uses: actions/upload-artifact@v2
        with:
          name: escapex-${{ runner.os }}
          path: |
            escapex/*.exe
            escapex/*.png
